Software-Meister-High-School-Community/MOIZA-Spring-Server

src/main/java/com/example/moizaspringserver/MoizaSpringServerApplication.java, src/main/java/com/example/moizaspringserver/global/config/JpaConfig.java, src/main/java/com/example/moizaspringserver/global/entity/BaseIdEntity.java, src/main/java/com/example/moizaspringserver/global/entity/BaseTimeEntity.java, src/main/java/com/example/moizaspringserver/global/entity/BaseTimeIdEntity.java
=> 🔀 :: (#6) BaseEntity 설정

src/main/java/com/example/moizaspringserver/domain/follow/domain/Follow.java, src/main/java/com/example/moizaspringserver/domain/follow/domain/entity/Follow.java, src/main/java/com/example/moizaspringserver/domain/follow/domain/repository/FollowRepository.java
=> 🔀 :: (#14) 팔로우 / 팔로워 엔티티 생성

src/main/java/com/example/moizaspringserver/domain/notification/domain/entity/NotificationEntity.java, src/main/java/com/example/moizaspringserver/domain/notification/domain/entity/NotificationList.java, src/main/java/com/example/moizaspringserver/domain/notification/domain/entity/NotificationListId.java, src/main/java/com/example/moizaspringserver/domain/notification/domain/repository/NotificationEntityRepository.java, src/main/java/com/example/moizaspringserver/domain/notification/domain/repository/NotificationListRepository.java
=> 🔀 :: (#23) 알림 엔티티 생성

src/main/java/com/example/moizaspringserver/domain/follow/entity/Follow.java, src/main/java/com/example/moizaspringserver/domain/follow/entity/FollowId.java, src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java
=> 🔀 :: (#32) 팔로우 엔티티 변경

src/main/java/com/example/moizaspringserver/domain/user/entity/UserSuspension.java, src/main/java/com/example/moizaspringserver/domain/user/repository/UserSuspensionRepository.java
=> 🔀 :: (#24) 유저 정지 엔티티 생성 

.gitignore
=> 🔀 :: (#40) DS_STORE gitignore

src/main/java/com/example/moizaspringserver/domain/comment/entity/Comment.java, src/main/java/com/example/moizaspringserver/domain/comment/repository/CommentRepository.java
=> 🔀 :: (#17) 댓글 엔티티

src/main/java/com/example/moizaspringserver/domain/category/entity/Category.java, src/main/java/com/example/moizaspringserver/domain/category/entity/FeedCategory.java, src/main/java/com/example/moizaspringserver/domain/category/entity/FeedCategoryId.java, src/main/java/com/example/moizaspringserver/domain/category/repository/CategoryRepository.java, src/main/java/com/example/moizaspringserver/domain/category/repository/FeedCategoryRepository.java, src/main/java/com/example/moizaspringserver/domain/feed/entity/LocalFeed.java, src/main/java/com/example/moizaspringserver/domain/feed/entity/PublicFeed.java, src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedCategoryRepository.java, src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedLikeRepository.java, src/main/java/com/example/moizaspringserver/domain/graduate/entity/GraduateVerifyingFile.java, src/main/java/com/example/moizaspringserver/domain/graduate/repository/GraduateVerifyingFileRepository.java, src/main/java/com/example/moizaspringserver/domain/like/entity/FeedLike.java, src/main/java/com/example/moizaspringserver/domain/like/entity/FeedLikeId.java, src/main/java/com/example/moizaspringserver/domain/like/repository/FeedLikeRepository.java
=> 🔀 :: (#43) Feed 엔티티 

src/main/java/com/example/moizaspringserver/global/error/ErrorResponse.java, src/main/java/com/example/moizaspringserver/global/error/GlobalExceptionHandler.java, src/main/java/com/example/moizaspringserver/global/error/exception/CustomException.java, src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
=> 🔀 :: (#45) ErrorHandler

src/main/java/com/example/moizaspringserver/domain/report/entity/CommentReport.java, src/main/java/com/example/moizaspringserver/domain/report/entity/FeedReport.java, src/main/java/com/example/moizaspringserver/domain/report/entity/UserReport.java
=> 🔀 :: (#50) 신고 Entity들 상속문제 해결

build.gradle, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java, src/main/resources/application.yml
=> 🔀 :: (#48) security 설정 

src/main/java/com/example/moizaspringserver/domain/auth/entity/RefreshToken.java, src/main/java/com/example/moizaspringserver/domain/auth/exception/RefreshTokenNotFoundException.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/AuthController.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/response/UserTokenRefreshResponse.java, src/main/java/com/example/moizaspringserver/domain/auth/repository/RefreshTokenRepository.java, src/main/java/com/example/moizaspringserver/domain/auth/service/TokenRefreshService.java, src/main/java/com/example/moizaspringserver/domain/user/entity/User.java, src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java, src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
=> 🔀 :: (#59) 토큰 재발급 API

src/main/java/com/example/moizaspringserver/domain/auth/exception/PasswordMismatchException.java, src/main/java/com/example/moizaspringserver/domain/auth/facade/AuthFacade.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/AuthController.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/request/UserSignInInformation.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/request/UserSignInRequest.java, src/main/java/com/example/moizaspringserver/domain/auth/service/TokenRefreshService.java, src/main/java/com/example/moizaspringserver/domain/auth/service/UserSignInService.java, src/main/java/com/example/moizaspringserver/domain/user/entity/User.java, src/main/java/com/example/moizaspringserver/domain/user/entity/UserDeviceToken.java, src/main/java/com/example/moizaspringserver/domain/user/repository/UserDeviceTokenRepository.java, src/main/java/com/example/moizaspringserver/global/config/PropertiesConfig.java, src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java, src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java, src/main/java/com/example/moizaspringserver/global/security/properties/JwtProperties.java, src/main/resources/application.yml
=> 🔀 :: (#63) 유저 로그인 

src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/request/UserSignInRequest.java, src/main/java/com/example/moizaspringserver/domain/auth/service/UserSignInService.java
=> 🔀 :: (#80) 로그인 에러 해결 

src/main/java/com/example/moizaspringserver/domain/category/entity/FeedCategoryId.java, src/main/java/com/example/moizaspringserver/domain/follow/entity/FollowId.java, src/main/java/com/example/moizaspringserver/domain/like/entity/FeedLikeId.java, src/main/java/com/example/moizaspringserver/domain/notification/entity/NotificationListId.java, src/main/java/com/example/moizaspringserver/domain/report/entity/CommentReportId.java, src/main/java/com/example/moizaspringserver/domain/report/entity/FeedReportId.java, src/main/java/com/example/moizaspringserver/domain/report/entity/UserReportId.java
=> 🔀 :: (#78) 복합키를 사용하는 엔티티 메소드 재정의

src/main/java/com/example/moizaspringserver/domain/follow/presentation/FollowController.java, src/main/java/com/example/moizaspringserver/domain/follow/presentation/dto/response/FollowingInfo.java, src/main/java/com/example/moizaspringserver/domain/follow/presentation/dto/response/GetAllFollowingResponse.java, src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java, src/main/java/com/example/moizaspringserver/domain/follow/service/FollowService.java
=> 🔀 :: (#70) 팔로잉 가져오기 API

src/main/java/com/example/moizaspringserver/domain/user/presentation/UserController.java, src/main/java/com/example/moizaspringserver/domain/user/presentation/dto/response/UserListResponse.java, src/main/java/com/example/moizaspringserver/domain/user/presentation/dto/response/UserResponse.java, src/main/java/com/example/moizaspringserver/domain/user/repository/UserRepository.java, src/main/java/com/example/moizaspringserver/domain/user/service/QueryUserListService.java, src/main/java/com/example/moizaspringserver/domain/user/service/SearchUserService.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
=> 🔀 :: (#84) 전체 유저 검색 API

build.gradle, src/main/java/com/example/moizaspringserver/MoizaSpringServerApplication.java, src/main/java/com/example/moizaspringserver/domain/auth/entity/EmailCode.java, src/main/java/com/example/moizaspringserver/domain/auth/entity/EmailCodeLimit.java, src/main/java/com/example/moizaspringserver/domain/auth/exception/AuthCodeAlreadyVerifiedException.java, src/main/java/com/example/moizaspringserver/domain/auth/exception/EmailCodeRequestOverLimitException.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/AuthController.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/request/SendEmailAuthCodeRequest.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/response/SendEmailAuthCodeResponse.java, src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/response/SendEmailCodeResponse.java, src/main/java/com/example/moizaspringserver/domain/auth/repository/EmailCodeLimitRepository.java, src/main/java/com/example/moizaspringserver/domain/auth/repository/EmailCodeRepository.java, src/main/java/com/example/moizaspringserver/domain/auth/service/SendEmailAuthCodeService.java, src/main/java/com/example/moizaspringserver/global/aws/config/SesConfig.java, src/main/java/com/example/moizaspringserver/global/aws/properties/AwsProperties.java, src/main/java/com/example/moizaspringserver/global/aws/util/SesUtil.java, src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java, src/main/resources/application.yml
테스트해봤는데 잘되고 템플릿은 추후에 설정할게요
딴 pr은 요거 머지되면 올림
터지는건 이거때문
=> 🔀 :: (#73) 이메일 인증코드 발송

src/main/java/com/example/moizaspringserver/domain/follow/entity/Follow.java, src/main/java/com/example/moizaspringserver/domain/follow/exception/FollowAlreadyExistsException.java, src/main/java/com/example/moizaspringserver/domain/follow/presentation/FollowController.java, src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java, src/main/java/com/example/moizaspringserver/domain/follow/service/FollowEstablishService.java, src/main/java/com/example/moizaspringserver/domain/follow/service/FollowInquireService.java, src/main/java/com/example/moizaspringserver/domain/follow/service/FollowQueryService.java, src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
=> 🔀 :: (#85) 팔로우 추가 API

src/main/resources/application.yml
=> 🔀 :: (#93) yml 세팅 

src/main/java/com/example/moizaspringserver/domain/feed/entity/LocalFeed.java, src/main/java/com/example/moizaspringserver/domain/feed/presenstation/FeedController.java, src/main/java/com/example/moizaspringserver/domain/feed/presenstation/dto/request/LocalFeedRequest.java, src/main/java/com/example/moizaspringserver/domain/feed/service/UpdateLocalFeedService.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
close #106
게시글 임시저장 API가 없는 관계로 테스트는 생략하였습니다.
=> 🔀 :: (#106) 임시 저장 게시글 수정 API

build.gradle, src/main/java/com/example/moizaspringserver/global/config/querydsl/QuerydslConfig.java
=> 🔀 :: (#126) QueryDsl 세팅

src/main/java/com/example/moizaspringserver/domain/follow/exception/NoSuchFollowException.java, src/main/java/com/example/moizaspringserver/domain/follow/presentation/FollowController.java, src/main/java/com/example/moizaspringserver/domain/follow/service/FollowDeleteService.java, src/main/java/com/example/moizaspringserver/domain/follow/service/FollowDiscardService.java, src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
=> 🔀 :: (#97) 팔로우 취소 API

src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java, src/main/java/com/example/moizaspringserver/global/filter/ExceptionFilter.java, src/main/java/com/example/moizaspringserver/global/filter/FilterConfig.java
=> 🔀 :: (#102) 핸들러 추가

src/main/java/com/example/moizaspringserver/domain/feed/presenstation/FeedController.java, src/main/java/com/example/moizaspringserver/domain/feed/service/DeleteLocalFeedService.java, src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
=> 🔀 :: (#108) 임시 저장 게시글 삭제 API
